2020-09-05 19:41:36.742 [INFO ] io.lettuce.core.protocol.CommandHandler - null Unexpected exception during request: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2020-09-05 19:41:38.827 [INFO ] io.lettuce.core.protocol.ConnectionWatchdog - Reconnecting, last destination was /10.10.10.227:6381
2020-09-05 19:41:44.483 [INFO ] io.lettuce.core.protocol.ConnectionWatchdog - Reconnecting, last destination was 10.10.10.227:6381
2020-09-05 19:41:52.053 [INFO ] io.lettuce.core.protocol.ConnectionWatchdog - Reconnecting, last destination was 10.10.10.227:6381
2020-09-05 19:42:00.371 [INFO ] io.lettuce.core.protocol.ConnectionWatchdog - Reconnecting, last destination was 10.10.10.227:6381
2020-09-05 19:42:16.841 [INFO ] io.lettuce.core.protocol.ConnectionWatchdog - Reconnecting, last destination was 10.10.10.227:6381
2020-09-05 19:42:39.745 [INFO ] com.alibaba.druid.pool.DruidAbstractDataSource - {dataSource-1} failContinuous is true
2020-09-05 19:42:42.935 [INFO ] org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler - Shutting down ExecutorService 'taskScheduler'
2020-09-05 19:42:42.940 [INFO ] org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor - Shutting down ExecutorService 'applicationTaskExecutor'
2020-09-05 19:42:43.204 [INFO ] org.mongodb.driver.connection - Closed connection [connectionId{localValue:500, serverValue:1003}] to 10.10.10.227:27019 because there was a socket exception raised on another connection from this pool.
2020-09-05 19:42:43.213 [INFO ] com.alibaba.druid.pool.DruidDataSource - {dataSource-1} closing ...
2020-09-05 19:42:43.230 [INFO ] com.alibaba.druid.pool.DruidDataSource - {dataSource-1} closed
